# [shell]
# program = "tmux"
# args = ["new-session", "-A", "-s", "main"]

# import = [
#     "~/.config/alacritty/themes/themes/campbell.toml"
# ]
    
[window]
dimensions = { columns = 100, lines = 24 }
padding = { x = 20, y = 20 }

[font]
size = 12.5
offset = { x = 0, y = 0}
normal = { family = "JetBrainsMonoNL Nerd Font Mono"}

# [colors.primary]
# background = "#080808"
# foregound = ""

[terminal]
osc52 = "CopyPaste"
# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
