# [shell]
# program = "tmux"
# args = ["new-session", "-A", "-s", "main"]

import = [
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  "~/.config/alacritty/themes/tokyonight.toml"
]
    
[window]
dimensions = { columns = 100, lines = 24 }
padding = { x = 20, y = 20 }

[font]
size = 12.5
offset = { x = 0, y = 0}
normal = { family = "JetBrainsMonoNL Nerd Font Mono"}

