# [shell]
# program = "tmux"
# args = ["new-session", "-A", "-s", "main"]

import = [
  "~/.config/alacritty/themes/current_theme.toml"
]
    
[window]
dimensions = { columns = 100, lines = 24 }
padding = { x = 20, y = 20 }

[font]
size = 12.5
offset = { x = 0, y = 0}
normal = { family = "JetBrainsMonoNL Nerd Font Mono"}

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
]

[env]
TERM = "xterm-256color"
