return {}
-- return
-- {
--   'akinsho/bufferline.nvim',
--   version = "*",
--   dependencies = 'nvim-tree/nvim-web-devicons',
--   config = function()
--     local bufferline = require("bufferline")
--     bufferline.setup {
--       options = {
--         diagnostics = "nvim_lsp"
--       }
--     }
--     require 'which-key'.register({
--       ["<leader>b"] = {
--         name = "+buffer",
--         p = { "<cmd>:BufferLinePick<cr>", "Buffer pick" },
--         x = { "<cmd>:bdelete<cr>", "Buffer delete" },
--         c = {
--           name = "+close",
--           c = { "<cmd>:BufferLinePickClose<cr>", "Buffer pick close" },
--           o = { "<cmd>:BufferLineCloseOthers<cr>", "Buffer close others" },
--           l = { "<cmd>:BufferLineCloseRight<cr>", "Buffer close right" },
--           h = { "<cmd>:BufferLineCloseLeft<cr>", "Buffer close left" },
--         },
--
--
--       },
--     })
--
--     require('transparent').clear_prefix('BufferLine')
--
--     -- vim.keymap.set('n', '<leader>bp', ":BufferLinePick<CR>", { desc = "Buffer pick" })
--     -- vim.keymap.set('n', '<leader>bcc', ":BufferLinePickClose<CR>", { desc = "Buffer pick close" })
--     -- vim.keymap.set('n', '<leader>bco', ":BufferLineCloseOthers<CR>", { desc = "Buffer close others" })
--     -- vim.keymap.set('n', '<leader>bcl', ":BufferLineCloseRight<CR>", { desc = "Buffer close right" })
--     -- vim.keymap.set('n', '<leader>bch', ":BufferLineCloseLeft<CR>", { desc = "Buffer close left" })
--   end
-- }
